import faker from 'faker';

export const FIND_USER_RESPONSE = () => {
    const login = faker.internet.userName();
    return {
      "login": login,
      "id": faker.random.number,
      "node_id": faker.random.alphaNumeric(16),
      "avatar_url": "https://some-content-url.com",
      "url": `https://api.github.com/users/${login}`,
      "html_url": `https://github.com/${login}`,
      "followers_url": `https://api.github.com/users/${login}/followers`,
      "following_url": `https://api.github.com/users/${login}/following{/other_user}`,
      "gists_url": `https://api.github.com/users/${login}/gists{/gist_id}`,
      "starred_url": `https://api.github.com/users/${login}/starred{/owner}{/repo}`,
      "subscriptions_url": `https://api.github.com/users/${login}/subscriptions`,
      "organizations_url": `https://api.github.com/users/${login}/orgs`,
      "repos_url": `https://api.github.com/users/${login}/repos`,
      "events_url": `https://api.github.com/users/${login}/events{/privacy}`,
      "received_events_url": `https://api.github.com/users/${login}/received_events`,
      "type": "User",
      "site_admin": false,
      "name": faker.name.findName(),
      "company": faker.company.companyName(),
      "blog": "",
      "location": faker.address.city(),
      "email": faker.internet.email(),
      "hireable": null,
      "bio": faker.random.words(10),
      "twitter_username": null,
      "public_repos": faker.random.number(100),
      "public_gists": faker.random.number(10),
      "followers": faker.random.number(20),
      "following": faker.random.number(50),
      "created_at": Date.now(),
      "updated_at": Date.now(),
    }
}

export const FIND_STARRED_REPOSITORIES = () => {
    const url = `https://api.github.com/users/:login`;
    return FIND_REPOSITORIES(url);
}

export const FIND_REPOSITORIES = (url = `https://api.github.com/users/:login`) => {
    const login = faker.internet.userName();
    const repoName = faker.random.words(3);
    const repo = repoName.split(' ').join('-');
    url = url.replace(':login', login);
    return {
        url,
        data: [
            {
              "id": 158898449,
              "node_id": faker.random.alphaNumeric(32),
              "name": repo,
              "full_name": `${login}/${repo}`,
              "private": false,
              "owner": {
                "login": login,
                "id": 7198068,
                "node_id": faker.random.alphaNumeric(20),
                "avatar_url": "https://avatars0.githubusercontent.com/u/7198068?v=4",
                "gravatar_id": "",
                "url": `${url}/${login}`,
                "html_url": `https://github.com/${login}`,
                "followers_url": `${url}/${login}/followers`,
                "following_url": `${url}/${login}/following{/other_user}`,
                "gists_url": `${url}/${login}/gists{/gist_id}`,
                "starred_url": `${url}/${login}/starred{/owner}{/repo}`,
                "subscriptions_url": `${url}/${login}/subscriptions`,
                "organizations_url": `${url}/${login}/orgs`,
                "repos_url": `${url}/${login}/repos`,
                "events_url": `${url}/${login}/events{/privacy}`,
                "received_events_url": `${url}/${login}/received_events`,
                "type": "User",
                "site_admin": false
              },
              "html_url": "https://github.com/${login}/${repo}",
              "description": repoName,
              "fork": false,
              "url": `https://api.github.com/repos/${login}/${repo}`,
              "forks_url": `https://api.github.com/repos/${login}/${repo}/forks`,
              "keys_url": `https://api.github.com/repos/${login}/${repo}/keys{/key_id}`,
              "collaborators_url": `https://api.github.com/repos/${login}/${repo}/collaborators{/collaborator}`,
              "teams_url": `https://api.github.com/repos/${login}/${repo}/teams`,
              "hooks_url": `https://api.github.com/repos/${login}/${repo}/hooks`,
              "issue_events_url": `https://api.github.com/repos/${login}/${repo}/issues/events{/number}`,
              "events_url": `https://api.github.com/repos/${login}/${repo}/events`,
              "assignees_url": `https://api.github.com/repos/${login}/${repo}/assignees{/user}`,
              "branches_url": `https://api.github.com/repos/${login}/${repo}/branches{/branch}`,
              "tags_url": `https://api.github.com/repos/${login}/${repo}/tags`,
              "blobs_url": `https://api.github.com/repos/${login}/${repo}/git/blobs{/sha}`,
              "git_tags_url": `https://api.github.com/repos/${login}/${repo}/git/tags{/sha}`,
              "git_refs_url": `https://api.github.com/repos/${login}/${repo}/git/refs{/sha}`,
              "trees_url": `https://api.github.com/repos/${login}/${repo}/git/trees{/sha}`,
              "statuses_url": `https://api.github.com/repos/${login}/${repo}/statuses/{sha}`,
              "languages_url": `https://api.github.com/repos/${login}/${repo}/languages`,
              "stargazers_url": `https://api.github.com/repos/${login}/${repo}/stargazers`,
              "contributors_url": `https://api.github.com/repos/${login}/${repo}/contributors`,
              "subscribers_url": `https://api.github.com/repos/${login}/${repo}/subscribers`,
              "subscription_url": `https://api.github.com/repos/${login}/${repo}/subscription`,
              "commits_url": `https://api.github.com/repos/${login}/${repo}/commits{/sha}`,
              "git_commits_url": `https://api.github.com/repos/${login}/${repo}/git/commits{/sha}`,
              "comments_url": `https://api.github.com/repos/${login}/${repo}/comments{/number}`,
              "issue_comment_url": `https://api.github.com/repos/${login}/${repo}/issues/comments{/number}`,
              "contents_url": `https://api.github.com/repos/${login}/${repo}/contents/{+path}`,
              "compare_url": `https://api.github.com/repos/${login}/${repo}/compare/{base}...{head}`,
              "merges_url": `https://api.github.com/repos/${login}/${repo}/merges`,
              "archive_url": `https://api.github.com/repos/${login}/${repo}/{archive_format}{/ref}`,
              "downloads_url": `https://api.github.com/repos/${login}/${repo}/downloads`,
              "issues_url": `https://api.github.com/repos/${login}/${repo}/issues{/number}`,
              "pulls_url": `https://api.github.com/repos/${login}/${repo}/pulls{/number}`,
              "milestones_url": `https://api.github.com/repos/${login}/${repo}/milestones{/number}`,
              "notifications_url": `https://api.github.com/repos/${login}/${repo}/notifications{?since,all,participating}`,
              "labels_url": `https://api.github.com/repos/${login}/${repo}/labels{/name}`,
              "releases_url": `https://api.github.com/repos/${login}/${repo}/releases{/id}`,
              "deployments_url": `https://api.github.com/repos/${login}/${repo}/deployments`,
              "created_at": "2018-11-24T03:18:01Z",
              "updated_at": "2018-11-24T03:24:58Z",
              "pushed_at": "2018-11-24T03:24:56Z",
              "git_url": `git://github.com/${login}/${repo}.git`,
              "ssh_url": `git@github.com:${login}/${repo}.git`,
              "clone_url": `https://github.com/${login}/${repo}.git`,
              "svn_url": `https://github.com/${login}/${repo}`,
              "homepage": "",
              "size": 37,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "Shell",
              "has_issues": false,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": false,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": null,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": {
                "key": "mit",
                "name": "MIT License",
                "spdx_id": "MIT",
                "url": "https://api.github.com/licenses/mit",
                "node_id": faker.random.alphaNumeric(16)
              },
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master"
            },
        ]          
    }
}